@startuml

title Процесс записи пациента на приём (AS-IS)

actor "Пациент" as Patient
actor "Сотрудник ресепшена" as ReceptionStaff

rectangle "Общий диск" as SharedDrive {
  database "Excel файл \n (Журнал записей)" as ExcelJournal
  database "Сканы анкеты \n (PDF/JPG)" as Scans
}

Patient -> ReceptionStaff : Звонок/Личный визит \n [ФИО, телефон, электронная почта, дата рождения,\n желаемая дата, жалобы, адрес прописки, \n место работы или учёбы, \n хронические заболевания]
ReceptionStaff -> ExcelJournal : Ручной ввод данных \n [ФИО, телефон, дата рождения,\nдата/время приёма, жалобы,\nконтактные данные]
ReceptionStaff -> Patient : Подтверждение записи \n [Дата, время, кабинет]
ReceptionStaff -> Scans : Сканирование анкеты \n [ФИО, телефон, электронная почта, дата рождения,\n желаемая дата, жалобы, адрес прописки, \n место работы или учёбы, \n хронические заболевания]

@enduml